### ISSUE TITLE
Crash issue when i increase the concurrency connection. Could you help to check it?

### ISSUE THREAD

**Issue by haiylin** [mattn/go-oci8#104]
runtime stack:
runtime.gothrow(0x9e31b0, 0x2a)
        /usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 4033 [syscall, locked to thread]:
runtime.cgocall_errno(0x402420, 0xc20c174440, 0x0)
        /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc20c174420 sp=0xc20c1743f8
plug-in/go-oci8._Cfunc_WrapOCILogon(0x7f19a011c660, 0x7f19a0185f30, 0x7f19a0119dd0, 0x7f1900000008, 0x7f19a016fe30, 0x9, 0x7f19a0176d80, 0x6, 0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/plug-in/go-oci8/:271 +0x63 fp=0xc20c174440 sp=0xc20c174420
plug-in/go-oci8.(*OCI8Driver).Open(0xe6a7b8, 0xc20803b237, 0x19, 0x0, 0x0, 0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/plug-in/go-oci8/oci8.go:535 +0x5cd fp=0xc20c1745b0 sp=0xc20c174440
database/sql.(*DB).conn(0xc2088bafa0, 0x2, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:664 +0x506 fp=0xc20c174708 sp=0xc20c1745b0
database/sql.(*DB).Ping(0xc2088bafa0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:462 +0x3a fp=0xc20c174740 sp=0xc20c174708
common.(*DbPool).GetConn(0xc20803b980, 0x31, 0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/common/public.go:167 +0x19d fp=0xc20c1748c0 sp=0xc20c174740
dao.GetNumberOfMeetingIn30Days(0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/dao/dsStap.go:465 +0x90 fp=0xc20c1749b0 sp=0xc20c1748c0
controllers.DataService.GetLast30DaysMeeting(0xc20b5c1920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/controllers/apiMain.go:128 +0x141 fp=0xc20c174ac0 sp=0xc20c1749b0
controllers.(*DataService).GetLast30DaysMeeting(0xc20b608e40, 0x0, 0x0)
        <autogenerated>:5 +0xb2 fp=0xc20c174b18 sp=0xc20c174ac0
runtime.call32(0x9305b0, 0xc20b5f67a0, 0x800000018)
        /usr/local/go/src/runtime/asm_amd64.s:402 +0x45 fp=0xc20c174b40 sp=0xc20c174b18
reflect.Value.call(0x92fac0, 0xc20b608e40, 0x2753, 0x933500, 0x4, 0xc20c174f18, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:419 +0x10e5 fp=0xc20c174e58 sp=0xc20c174b40
reflect.Value.Call(0x92fac0, 0xc20b608e40, 0x2753, 0xc20c174f18, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:296 +0xbc fp=0xc20c174eb8 sp=0xc20c174e58
plug-in/gorest.prepareServe(0xc20b5c1920, 0x98e430, 0x14, 0x934fc0, 0x3, 0xc2081282c1, 0x1c, 0x0, 0x0, 0xc2081282c1, ...)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/plug-in/gorest/reflect.go:391 +0x16aa fp=0xc20c175520 sp=0xc20c174eb8
plug-in/gorest.manager.ServeHTTP(0xc208185110, 0xc208185140, 0x7f19f028aaa0, 0xc20b5e2200, 0xc209a69110)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/plug-in/gorest/gorest.go:215 +0x638 fp=0xc20c175a68 sp=0xc20c175520
plug-in/gorest.(*manager).ServeHTTP(0xc2081171f0, 0x7f19f028aaa0, 0xc20b5e2200, 0xc209a69110)
        <autogenerated>:6 +0xbd fp=0xc20c175aa0 sp=0xc20c175a68
common.(*ApacheLoggingHandler).ServeHTTP(0xc208187540, 0x7f19f0281dc8, 0xc208fc90e0, 0xc209a69110)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/common/handleInitail.go:82 +0x294 fp=0xc20c175b80 sp=0xc20c175aa0
common.(*authenticationFilter).ServeHTTP(0xc208143c50, 0x7f19f0281dc8, 0xc208fc90e0, 0xc209a69110)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/common/authenticationFilter.go:40 +0x210 fp=0xc20c175c58 sp=0xc20c175b80
net/http.(*ServeMux).ServeHTTP(0xc20803aab0, 0x7f19f0281dc8, 0xc208fc90e0, 0xc209a69110)
        /usr/local/go/src/net/http/server.go:1541 +0x17d fp=0xc20c175cb0 sp=0xc20c175c58
net/http.serverHandler.ServeHTTP(0xc208101380, 0x7f19f0281dc8, 0xc208fc90e0, 0xc209a69110)
        /usr/local/go/src/net/http/server.go:1703 +0x19a fp=0xc20c175d08 sp=0xc20c175cb0
net/http.(*conn).serve(0xc209379360)
/usr/local/go/src/net/http/server.go:1204 +0xb57 fp=0xc20c175fd8 sp=0xc20c175d08
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20c175fe0 sp=0xc20c175fd8
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by haiylin** [comment]
After I applied the new code, found the issue is resolved. Thanks!
