### ISSUE TITLE
error in runtime on windows x64

### ISSUE THREAD

**Issue by edwardborst** [mattn/go-oci8#173]
Hi, 
I have installed oracle instant client 12.2 64bit in c:\oracle\instantclient_2_2
installed mingw etc. 
go-oci8 installed/compiled fine. no erros.

Also go build main.go went fine. no errors.
but now when running go run main.go I get the following error:
```
go run main.go
Exception 0xc0000005 0x0 0xb971a6 0x5adc70
PC=0x5adc70
signal arrived during external code execution

github.com/mattn/go-oci8._Cfunc_WrapOCIEnvCreate(0x1, 0x0, 0x0, 0x0, 0x0)
        github.com/mattn/go-oci8/_obj/_cgo_gotypes.go:797 +0x67
github.com/mattn/go-oci8.(*OCI8Driver).Open(0x5e31d8, 0x5388e1, 0x53, 0x0, 0x0, 0x0, 0x0)
        p:/projects/src/github.com/mattn/go-oci8/oci8.go:664 +0xf8
database/sql.(*DB).conn(0xc04203e1e0, 0x5b2140, 0xc04203a1d0, 0x1, 0xa0, 0x5285a0, 0x0)
        C:/Go/src/database/sql/sql.go:965 +0x14d
database/sql.(*DB).query(0xc04203e1e0, 0x5b2140, 0xc04203a1d0, 0x53365c, 0x16, 0x0, 0x0, 0x0, 0x4b4d01, 0xc042031e70, ...)
        C:/Go/src/database/sql/sql.go:1245 +0x62
database/sql.(*DB).QueryContext(0xc04203e1e0, 0x5b2140, 0xc04203a1d0, 0x53365c, 0x16, 0x0, 0x0, 0x0, 0x429b56, 0x538f20, ...)
        C:/Go/src/database/sql/sql.go:1227 +0xbf
database/sql.(*DB).Query(0xc04203e1e0, 0x53365c, 0x16, 0x0, 0x0, 0x0, 0x0, 0xc042031ee0, 0xc042076088)
        C:/Go/src/database/sql/sql.go:1241 +0x89
main.main()
        P:/projects/src/test/oradbtest/main.go:17 +0xc4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 19 [chan receive]:
database/sql.(*DB).connectionOpener(0xc04203e1e0)
        C:/Go/src/database/sql/sql.go:837 +0x51
created by database/sql.Open
        C:/Go/src/database/sql/sql.go:582 +0x219
rax     0x0
rbx     0xc042031a58
rcx     0x7ffd08
rdi     0x7ffd10
rsi     0x0
rbp     0xc042032000
rsp     0x7ffca8
r8      0x0
r9      0x0
r10     0x11e532b
r11     0x7ffc30
r12     0x1
r13     0x0
r14     0x0
r15     0xf2
rip     0x5adc70
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```

**Comment by mattn** [comment]
what output of `go env`?

**Comment by edwardborst** [comment]
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=p:\projects\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\EDWARD~1.BOR\AppData\Local\Temp\go-build994949359=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

**Comment by mattn** [comment]
what version of go do you use?

**Comment by edwardborst** [comment]
go version go1.8.1 windows/amd64

**Comment by mattn** [comment]
```
set PATH=c:\oracle\instantclient_2_2;%PATH%
```
And please try again.

**Comment by edwardborst** [comment]
that is already in the path.

**Comment by mattn** [comment]
did you try first path in the %PATH%.

**Comment by edwardborst** [comment]
yes:
PATH=c:\oracle\instantclient_12_2;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Interactive Intelligence\ININ Trace Initialization\;C:\Program Files (x86)\Interactive Intelligence\ICUserApps\;C:\Program Files\Citrix\System32\;C:\Program Files\Citrix\ICAService\;C:\Program Files\Citrix\Virtual Desktop Agent\;C:\Program Files (x86)\Interactive Intelligence\BusinessManagerApps\;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\;C:\Program......

**Comment by mattn** [comment]
show me your code, please

**Comment by edwardborst** [comment]
```
package main

import (
	"database/sql"
	"log"

	_ "github.com/mattn/go-oci8"
)

func main() {
	db, err := sql.Open("oci8", "test/test@dev12c-scan1.dev.benelux.intra.corp:1521/alitest")
	if err != nil {
		log.Println("error in Open")
		log.Fatal(err)
	}

	rows, err := db.Query("select 'bla' from dual")
	if err != nil {
		log.Println("error in Query")
		log.Fatal(err)
	}
	for rows.Next() {
		var i int
		err = rows.Scan(&i)
		if err != nil {
			log.Fatal(err)
		}
		println(i)
	}
}
```

**Comment by mattn** [comment]
Do you set environment variable NLS_LANG?

**Comment by edwardborst** [comment]
Tried with and without, but I see no difference.

**Comment by mattn** [comment]
I can't reproduce it. So please try debug.

1. Open oci8.go in text editor.
2. Find function WrapOCIEnvCreate.
3. Replace the function to following.
4. `go build main.go`
5. run

```c
static ret2ptr
WrapOCIEnvCreate(ub4 mode, size_t extra) {
  OCIEnv *env;
  ub2 charsetid = 0;
  ret2ptr vvv = {NULL, NULL, 0};
  void *ptr;
  
  puts("debug1");
  if (extra == 0)  {
    ptr = NULL;
  } else {
    ptr = &vvv.extra;
  }
  puts("debug2");
  if (getenv("NLS_LANG") == NULL && !OCIEnvInit(&env, OCI_DEFAULT, 0, NULL)) {
    puts("debug3");
    charsetid = OCINlsCharSetNameToId(env, (const oratext*)"AL32UTF8");
    puts("debug4");
    OCIHandleFree(env, OCI_HTYPE_ENV);
    puts("debug5");
  }

  puts("debug6");
  vvv.rv = OCIEnvNlsCreate(
    (OCIEnv**)(&vvv.ptr),
    mode,
    NULL,
    NULL,
    NULL,
    NULL,
    extra,
    ptr,
    charsetid,
    charsetid);
  puts("debug7");
  return vvv;
}


```

**Comment by edwardborst** [comment]
```
debug1
debug2
Exception 0xc0000005 0x0 0xb971fe 0x5adcc0
PC=0x5adcc0
signal arrived during external code execution

github.com/mattn/go-oci8._Cfunc_WrapOCIEnvCreate(0x1, 0x0, 0x0, 0x0, 0x0)
        github.com/mattn/go-oci8/_obj/_cgo_gotypes.go:798 +0x67
github.com/mattn/go-oci8.(*OCI8Driver).Open(0x5e31d8, 0x5388e1, 0x53, 0x0, 0x0, 0x0, 0x0)
        p:/projects/src/github.com/mattn/go-oci8/oci8.go:672 +0xf8
database/sql.(*DB).conn(0xc04203e1e0, 0x5b2140, 0xc04203a1d0, 0x1, 0xa0, 0x5285a0, 0x0)
        C:/Go/src/database/sql/sql.go:965 +0x14d
database/sql.(*DB).query(0xc04203e1e0, 0x5b2140, 0xc04203a1d0, 0x53365c, 0x16, 0x0, 0x0, 0x0, 0x4b4d01, 0xc042031e70, ...)
        C:/Go/src/database/sql/sql.go:1245 +0x62
database/sql.(*DB).QueryContext(0xc04203e1e0, 0x5b2140, 0xc04203a1d0, 0x53365c, 0x16, 0x0, 0x0, 0x0, 0x429b56, 0x538f20, ...)
        C:/Go/src/database/sql/sql.go:1227 +0xbf
database/sql.(*DB).Query(0xc04203e1e0, 0x53365c, 0x16, 0x0, 0x0, 0x0, 0x0, 0xc042031ee0, 0xc042076088)
        C:/Go/src/database/sql/sql.go:1241 +0x89
main.main()
        P:/projects/src/Arval/oradbtest/main.go:17 +0xc4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 19 [chan receive]:
database/sql.(*DB).connectionOpener(0xc04203e1e0)
        C:/Go/src/database/sql/sql.go:837 +0x51
created by database/sql.Open
        C:/Go/src/database/sql/sql.go:582 +0x219
rax     0x0
rbx     0xc042031a58
rcx     0x7ffd08
rdi     0xc042031a58
rsi     0x0
rbp     0x7ffd10
rsp     0x7ffca8
r8      0x0
r9      0x0
r10     0x10e5344
r11     0x7ffc30
r12     0xc042032000
r13     0x1
r14     0x0
r15     0xf2
rip     0x5adcc0
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```

**Comment by edwardborst** [comment]
this is without NLS_LANG
if I set NLS_LANG to al32utf8 I get:

```
go run main.go
debug1
debug2
debug6
Exception 0xc0000005 0x0 0xb9724e 0x5adce8
PC=0x5adce8
signal arrived during external code execution
.....
```

**Comment by mattn** [comment]
Hmm, can not reproduce.

**Comment by edwardborst** [comment]
are you using the latest version of instant client 64Bit on windows?

**Comment by mattn** [comment]
I use 12.1

**Comment by edwardborst** [comment]
instant client or full client?

**Comment by mattn** [comment]
instant client 12.1

**Comment by edwardborst** [comment]
will try that and let you know.

**Comment by edwardborst** [comment]
hmm no difference..
What could be different to your setup and mine? 
could you tell me what you have installed? compiler etc.... maybe it is something like that?

**Comment by mattn** [comment]
I use gcc bundled on msys2-mingw

```
gcc (Rev1, Built by MSYS2 project) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by edwardborst** [comment]
are you building from msys command (mingetty) or from a windows command session?

**Comment by mattn** [comment]
No, just add `c:/msys64/mingw64/bin` into `%PATH%`

**Comment by edwardborst** [comment]
whow, that strange, with this one it is working now.
I first got another error, but that was my code... 
Thanks for your support and keep up the good work!

For others having the same issue do the following:
download msys64. install mingw64 and base-devl packages with all the dependencies.
download oracle instant client 64bit with basic and sdk.
unpack both into the same directory.

now in a normal windows command session add the mingw64/bin to your path.
Also add the unpack directory for oracle instant client to your path.

install/reinstall go-oci8
now compile and run you go code.
